#!/usr/bin/env python
# -*-python-*-

import time
from os.path import join as pjoin

import tdrum

loaded_instruments = []

core = tdrum.Core()

sample_dir = pjoin("/home", "tower", "Composition", "Drum Samples", "NSA Custom Series Drumkit (Multi-Samples)")

def new_instrument(note, samples):
    i = tdrum.Instrument()

    for (velocity, filename) in samples:
        i.loadSample(filename, velocity)

    core.addInstrument(note, i)

new_instrument(10, [(64, pjoin(sample_dir, "Kick Drum Multi-Samples", "F065.wav")),
                    (65, pjoin(sample_dir, "Kick Drum Multi-Samples", "F066.wav"))])

new_instrument(11, [(64, pjoin(sample_dir, "Cymbal Multi-Samples", "01  12ACSM   [s].wav")),
                    (64, pjoin(sample_dir, "Cymbal Multi-Samples", "02  12ACSM   [s].wav")),
                    (64, pjoin(sample_dir, "Cymbal Multi-Samples", "03  12ACSM   [s].wav"))])

new_instrument(12, [(64, pjoin(sample_dir, "Cymbal Multi-Samples", "01  .8ACSM   [s].wav"))])

print "Jack registration successful:", core.registerJack()

try:
    while True:
        time.sleep(10)
except KeyboardInterrupt:
    pass

print "done"

